name: rearticle_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  fl_chart: ^0.66.0
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  intl: ^0.20.2
  in_app_purchase: ^3.1.13
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.9.1
  path_provider: ^2.1.2
  file_picker: ^8.0.0
  phosphor_flutter: ^2.1.0
  csv: ^6.0.0
  flutter_local_notifications: ^19.5.0
  open_filex: ^4.7.0
  google_fonts: ^6.3.2
  uuid: ^4.3.3
  pdf: ^3.11.3
  printing: ^5.14.3
  flutter_svg: ^2.2.2
  share_plus: ^10.0.0
  flutter_timezone: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_logo.png"